require('vis')
require('vis-alternate-file')
require('vis-fzf-open')

-- vis:command('set autoindent')
-- vis:command('set breakat')
-- vis:command('set change')
-- vis:command('set colorcolumn')
-- vis:command('set cursorline')
-- vis:command('set escdelay')
-- vis:command('set expandtab')
-- vis:command('set horizon')
-- vis:command('set ignorecase')
-- vis:command('set layout')
-- vis:command('set loadmethod')
-- vis:command('set numbers')
-- vis:command('set redrawtime')
-- vis:command('set relativenumbers')
-- vis:command('set savemethod')
-- vis:command('set shell')
-- vis:command('set showeof')
-- vis:command('set shownewlines')
-- vis:command('set showspaces')
-- vis:command('set showtabs')
-- vis:command('set syntax')
-- vis:command('set tabwidth')
-- vis:command('set theme')
-- vis:command('set wrapcolumn')

vis.events.subscribe(vis.events.INIT, function()
    vis:command('set autoindent on')
    vis:command('set escdelay 0')
    vis:command('set ignorecase on')
    vis:command('set layout h')
    vis:command('set loadmethod auto')
    vis:command('set redrawtime 0.0')
    vis:command('set shell /bin/sh')
    vis:command('set theme minimal-dark-clear')
end)

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
    -- vis:command('set breakat [a-z]')
    vis:command('set colorcolumn 0')
    vis:command('set savemethod auto')
    vis:command('set cursorline off')
    vis:command('set expandtab on')
    vis:command('set horizon 0')
    vis:command('set numbers off')
    vis:command('set relativenumbers on')
    -- vis:command('set showeof off')
    -- vis:command('set shownewlines off')
    -- vis:command('set showspaces off')
    -- vis:command('set showtabs off')
    vis:command('set syntax off')
    vis:command('set tabwidth 4')
    -- vis:command('set wrapcolumn 0')

    vis:map(vis.modes.NORMAL, " f", function()
        vis:command("fzf")
    end)
end)
